version: "3.8"

services:
  tina:
    # image: pitronumdev/tina:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:80"
    networks:
      - tina-dev
  pgsql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: tina
    ports:
      - "4001:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - tina-dev

networks:
  tina-dev:
